apiVersion: apps/v1
kind: Deployment
metadata:
  name: getsetmix-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getsetmix-nats
  template:
    metadata:
      labels:
        app: getsetmix-nats
    spec:
      containers:
        - name: nats
          image: nats:2.10.18
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 4222
          args:
            - "--js=0"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: getsetmix-nats
  ports:
    - name: client
      port: 4222
      targetPort: client
